package org.cytoscape.peMeasure.internal;

public class PEhelp extends javax.swing.JFrame {

    private String helpString;

    /**
     * Creates new form TieDieHelp
     */
    public PEhelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE).addContainerGap()));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PEhelp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void setText(int buttonNumber) {
      
        helpString =
                " Biggest Maximal Clique: \n\n"
                + "----\n"
                + " PPI(Protein Proetein Interaction) data obtained from   \n"
                + " high-throughput experimental techniques is usually liable \n"
                + " to contain a large number of spurious interactions \n"
                + "\n"
                + " The aim of this app is to  validate the interactions"
                + "before exploiting them for further analysis"
                + "\n"
                + "Tutorial :"
                + "Click on Apps menu \n"
                + "Click on ~PE Measure - 1.0~ which opens a tabbed panel in control panel \n"
                + "Select the network to be used and input reliability threshold \n"
                + "Select if you would like to have subnetwork filtered, extracted out"
                + "Click on the Run button \n"
                + "----\n"
                + "Find the new subnetwork created programmatically \n"
                + "and the corresponding edges highlighted in the input network \n\n" ;
        
                

        this.setTitle("PE Measure Help : ");
        
        jTextArea1.setText(helpString);
        jTextArea1.setCaretPosition(0);
    }
}
